### PR TITLE
Getting Out of JavaScript Fatigue

### PR DESCRIPTION
**Pull request by jrnail23**

### CODE REVIEW

**Comment by scottcorgan** [comment]
Thanks for the PR! Was there discussion around this?

**Comment by jrnail23** [comment]
@scottcorgan I just happened across that article this morning, and it ended up being something of a counterpoint to the "JavaScript Fatigue" article you already had on here.

**Comment by scottcorgan** [comment]
The link to Javascript Fatigue is to a Google search to show that there are too many articles. I'm open to add a link to something that shows disagreement about this topic.

**Comment by jrnail23** [comment]
gotcha, no problem :+1:

**Pull request closed without merging**
