### PR TITLE
Why I use Tape instead of Mocha and so should You

### PR DESCRIPTION
**Pull request by joseluisq**
An Interesting drama about Tape and Mocha testing https://medium.com/@boneskull/full-disclosure-i-m-a-maintainer-of-mocha-5d9ded373e10

### CODE REVIEW

**Comment by scottcorgan** [comment]
Did you see anything on Twitter? Looking to link to discussions of different views.

**Comment by joseluisq** [comment]
yep, https://twitter.com/_ericelliott/status/624554804581302272 and then https://twitter.com/izs/status/693318207768166400

**Comment by joseluisq** [comment]
These are some different views

**Comment by scottcorgan** [comment]
If there is a link to these conversations linked, I'm open to add that. I want to be able to link to somewhere that shows blatant disagreement.

**Comment by joseluisq** [comment]
I understand, but this is debatable.
Maybe this article sounds like "personal preference" but this is a reflexive post, because there are many interesting and relevant points about programming related to Javascript, Node, Testing and Unix philosophy.
I think that this type of articles doesn't should be to take in personal way. Unlike It is **another debatable article** of one of many different views.
Because, finally... **Community and Developers have the final decision to prefer either solution.**
I think that in this case, this fits in categorization of "drama". :smile:
P.D. _I use Mocha, Tape, Ava, Karma, Chai, etc in many cases._

Regards.

**Pull request closed without merging**
